# SOMMAIRE

## Romanji / Hiragana / Katakana
## JLPT5, 80+ Kanjis
## JLPT5, vocabulary











## ROMANJI-HIRAGANA-KATAKANA
romanji = ['a', 'i', 'u', 'e', 'o',
           'ka', 'ki', 'ku', 'ke', 'ko',
           'ga', 'gi', 'gu', 'ge', 'go',
           'sa', 'shi', 'su', 'se', 'so',
           'za', 'ji', 'zu', 'ze', 'zo',
           'ta', 'tchi', 'tsu', 'te', 'to',
           'da', 'ji', 'zu', 'de', 'do',
           'na', 'ni', 'nu', 'ne', 'no',
           'ha', 'hi', 'fu', 'he', 'ho',
           'ba', 'bi', 'bu', 'be', 'bo',
           'pa', 'pi', 'pu', 'pe', 'po',
           'ma', 'mi', 'mu', 'me', 'mo',
           'ra', 'ri', 'ru', 're', 'ro',
           'ya', 'yu', 'yo',
           'wa', 'wo', 'n'
]

hiragana = ['あ', 'い', 'う', 'え', 'お',
            'か', 'き', 'く', 'け', 'こ',
            'が', 'ぎ', 'ぐ', 'げ', 'ご',
            'さ', 'し', 'す', 'せ', 'そ',
            'ざ', 'じ', 'ず', 'ぜ', 'ぞ',
            'た', 'ち', 'つ', 'て', 'と',
            'だ', 'ぢ', 'づ', 'で', 'ど',
            'な', 'に', 'ぬ', 'ね', 'の',
            'は', 'ひ', 'ふ', 'ヘ', 'ほ',
            'ば', 'び', 'ぶ', 'べ', 'ぼ',
            'ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ',
            'ま', 'み', 'む', 'め', 'も',
            'ら', 'り', 'る', 'れ', 'ろ',
            'や', 'ゆ', 'よ',
            'わ', 'を', 'ん'
]


katakana = ['ア', 'イ', 'ウ', 'エ', 'オ',
            'カ', 'キ', 'ク', 'ケ', 'コ',
            'ガ', 'ギ', 'グ', 'ゲ', 'ゴ',
            'サ', 'シ', 'ス', 'セ', 'ソ',
            'ザ', 'ジ', 'ズ', 'ゼ', 'ゾ',
            'タ', 'チ', 'ツ', 'テ', 'ト',
            'ダ', 'ヂ', 'ヅ', 'デ', 'ド',
            'ナ', 'ニ', 'ヌ', 'ネ', 'ノ',
            'ハ', 'ヒ', 'フ', 'ヘ', 'ホ',
            'バ', 'ビ', 'ブ', 'ベ', 'ボ',
            'パ', 'ピ', 'プ', 'ペ', 'ポ',
            'マ', 'ミ', 'ム', 'メ', 'モ',
            'ラ', 'リ', 'ル', 'レ', 'ロ',
            'ヤ', 'ュ', 'ヨ',
            'ワ', 'ヲ', 'ン'
]



## JLPT5 - 80+ Kanjis
JLPT5_kanji_jap = [
    '日',
    '国',
    '人',
    '年',
    '大',
    '一',
    '二',
    '三',
    '四',
    '五',
    '六',
    '七',
    '八',
    '九',
    '十',
    '百',
    '千',
    '万',
    '本',
    '中',
    '長',
    '出',
    '時',
    '行',
    '見',
    '月',
    '後',
    '前',
    '生',
    '間',
    '上',
    '今',
    '金',
    '入',
    '学',
    '高',
    '円',
    '子',
    '外',
    '下',
    '来',
    '気',
    '小',
    '山',
    '話',
    '女',
    '北',
    '南',
    '東',
    '西',
    '午',
    '書',
    '先',
    '名',
    '川',
    '水',
    '半',
    '男',
    '電',
    '校',
    '語',
    '土',
    '木',
    '聞',
    '食',
    '車',
    '何',
    '毎',
    '白',
    '天',
    '母',
    '父',
    '火',
    '右',
    '左',
    '読',
    '友',
    '休',
    '雨',
    
    '校長',
    '校外',
    '語気',
    '土曜日',
    '毎日',
    '毎月',
    '白人',
    '生年',
    '入国',
    '入学',
    '入院',
    '電車',
    '母語',
    '火山',
]

JLPT5_kanji_fr = [
    '(ニチ|ひ) jour, soleil',
    '(コク) pays',
    '(ジン, ニン|ひと) personne',
    '(ネン) année',
    '(ダイ タイ|おお.きい) grand',
    '(イチ|ひと) 1',
    '(ニ|ふた, ふた.つ) 2',
    '(サン|み.つ) 3',
    '(シ|よ) 4',
    '(ゴ|いつ) 5',
    '(ロク|む.つ) 6',
    '(シチ|なな) 7',
    '(ハチ|や.つ) 8',
    '(キュウ|ここの) 9',
    '(ジュウ|とお) 10',
    '(ヒャク) 100',
    '(セン) 1000',
    '(マン, ヨロ) 10000',
    '(ホン) livre, origine, vrai',
    '(チュウ|なか) dedans, milieu',
    '(チョウ|なが.い) long, chef',
    '(シュツ(shutsu)|で.る) sortir, sortie',
    '(ジ|とき) heure',
    '(コウ, ギョウ|い.く, ゆ.く, ゆ.き) aller',
    '(ケン|み.る, み.える, み.せる) regarder, voir',
    '(ゲツ, ガツ) lune, mois',
    '(ゴ|うしろ, あと) après, derrière, ensuite',
    '(ゼン|まえ) avant, devant',
    '(セイ|い.きる) vie, naissance',
    '(カン|あいだ, ま) pendant | pendant, distance, intervalle',
    '(ジョウ|うえ) dessus, au-dessus',
    '(コン|いま) maintenant',
    '(キン|かね) or',
    '(ニュウ|い.れる) entrer, insérer',
    '(ガク, マナ) étude',
    '(コウ|たか.い) haut, cher',
    '(エン|まる.い) Yen, rond',
    '(シ ス ツ|こ) enfant',
    '(ガイ|そと) dehors',
    '(ゲ|した, さ.げる) en-dessous, descendre',
    '(ライ|きた.る) arrivée de qqch, qqch qui arrive (rainen : année prochaine)',
    '(キ|いき) esprit, âme',
    '(ショウ|ちい.さい) petit',
    '(ヤ) montagne',
    '(ワ|はな.す はなし) histoire, parler',
    '(ジョ|おんな) femme',
    '(キタ ホク) Nord',
    '(ナン|みなみ) Sud',
    '(ヒガ) Est',
    '(セイ|にし) Ouest "occident", Ouest',
    '(ゴ|うま) midi, cheval',
    '(ショ|か.く) écrire',
    '(セン マ|さき) avant, précédent',
    '(メイ|な) nom, réputation',
    '(カワ) rivière, flux',
    '(スイ|みず) eau',
    '(ハン) moitié',
    '(ダン|おとこ) homme',
    '(デン) électricité',
    '(コウ) école',
    '(ゴウ,かた.る) mot, langue',
    '(ド, ツ) sol, terre',
    '(モク|き) arbre, bois',
    '(ブン モン|き.く き.こえる) entendre, écouter, demander',
    '(ショク|く.う く.らう た.べる) nourriture, manger',
    '(クル, シャ) voiture, "en lien avec les pièces de voitures"',
    '(カ|なに なん) quoi, quelle, combien',
    '(マイ|ごと) chaque, tous les',
    '(ハク|しろ しら-) blanc',
    '(テン|あまつ) ciel, paradis',
    '(ボ|はは も) maman',
    '(フ|ちち) papa',
    '(カ|ひ -び) feu',
    '(ミギ) droite',
    '(サ ヒダリ) gauche',
    '(ドク|よ.む) lire',
    '(トモ) ami',
    '(キュウ|やす.む やす.まる やす.める) repos, sommeil, retraite',
    '(ウ|あめ あま-) pluie',

    '(コウチョウ) directeur d\'école, principal, proviseur',
    '(コウガイ) hors de l\'école, à l\'extérieur de l\'école',
    '(ゴウキ) intonation, accent',
    '(ドヨウビ) samedi',
    '(マイニチ) tous les jours, chaque jour',
    '(マイツキ) tous les mois, chaque mois',
    '(ハクジン) blanc, race blanche',
    '(セイネン) année de naissance, âge',
    '(ニュウコク) entrée sur le territoire, immigration',
    '(ニュウガク) entrée, admission (à l\'école)',
    '(ニュウイン) hospitalisation',
    '(デンシヤ) train électrique',
    '(ボゴ) langue maternelle',
    '(カザン) volcan',
]















## JLPT5, vocabulary

JLPT5_voc_jap = [
    '会う',
    '開',
    '上げる',
    '朝',
    '明日',
    '明後日',
    '足',
    '(あそこ)',
    '遊ぶ',
    '暖かい',
    '頭',
    '新しい',
    '新',
    '(あちら)',
    '暑い|厚い',
    '兄',
    '姉',
    '(あの)',
    '(アパート)',
    '浴びる',
    '危ない',
    '甘い',
    '余り',
    '青',
    '赤',
    '黄色',
    '紫',
    '明い',
    '秋',
    '誕生会',
    '青空',
    '見上げる',
    '朝御飯',
    '飴',
    '洗う',
    '歩く',
    '出歩く',
    '素足で歩く',
    '基',
    'いい/よい',
    'いいえ',
    '言う',
    '陰で悪口を言う',
    '家',
    'いかが|いくつ',
    'いくら',
    '池',
    '医者',
    '口',
    '悪',
    '椅子',
    '忙しい',
    '痛い',
    'いちばん',
    '五日',
    '九日',
    'いつ',
    '一緒',
    '緒',
    '何時も',
    '犬',
    '意味',
    '妹',
    '味',
    '味方',
    '嫌',
    '入口',
    '居る',
    '要る',
    '入れる',
    '色',
    'いろいろ',
    '薄い',
    '薄い服',
    '薄いコーヒー',
    '薄い色',
    '海賊',
    '王',
    '寝室',
    '台所',
    '魚',
    '馬',
    '英語',
    '飲む',
    '午前',
    '午後',
    '私',
    '起きる',
    '寝る',
    '牛',
    '牛乳',
    '牛肉',
    '零時',
    '庭',
    '会社',
    '猫',
    '机',
    '海',
    '窓',
    '卵',
    '歌',
    
    '歌う',
    '生まれる',
    '売る',
    '煩い',
    '上着',
    '絵',
    '映画',
    '映画館',
    '駅',
    'エレベーター',
    '鉛筆',
    '美味しい',
    '多い',
    '大勢',
    'お母さん',
    '菓子',
    '置く',
    '奥さん',
    'お酒',
    'お皿',
    '叔父',
    '教える',
    'お祖父さん',
    '押す',
    '遅い',
    'お茶',
    'お手洗い',
    'お父さん',
    '弟',
    '男の子',
    '一昨日',
    '一昨年',
    '大人',
    'お腹',
    '同じ',
    'お兄さん',
    'お姉さん',
    'お祖母さん',
    '伯母さん',
    'お風呂',
    'お弁当',
    '覚える',
    '重い',
    '面白い',
    '泳ぐ',
    '降りる',
    '終わる',
    '音楽',
    '女の子',
    '外国',
    '外国人',
    '階段',
    '買い物',
    '買い物リスト',
    '買い物に行く',
    '買う',
    '返す',
    '帰る',
    '罹る',
    '鍵',
    '学生',
    '電話を掛ける',
    '電話',
    '傘',
    '貸す',
    '風',
    '風邪',
    '家族',
    '方',
    '治し方',
    '歩き方',
    'カップ',
    '家庭',
    '彼女',
    '彼',
    '誰',
    '歳',
    '留学生',
    '学生証',
    '違い',
    '兄弟',
    '姉妹',
    '両親',
    '子供',
    '栖む',
    '出身',
    '冷たい',
    '寒い',
    '好き',
    '辛い',
    '食堂',
    '廉い',
    '隣',
    '昨日',
    '勉強する',
    '仕事',
    '食欲',
    '食費',
    '食物',
    '安い',

    '晩御飯',
    '嫌い',
    '世',
    '全て',
    '死に',
    '放つ',
    '全世界',
    '世界',
    '人間',
    '港',
    '村',
    '働く',
    '働きすぎ',
    '働き',
    '時間',
    '出発',
    '問題',
    '船',
    '停泊',
    '角',
    '鞄',
    '花瓶',
    '紙',
    'カメラ',
    '月曜日',
    '火曜日',
    '水曜日',
    '木曜日',
    '金曜日',
    '日曜日',
    '体',
    '借りる',
    '簡単',
    'カレー',
    '暦',
    '川/河',
    '可愛い',
    '漢字',
    '消える',
    'ギター',
    '汚い',
    '喫茶店',
    '切手',
    '切符',
    '今日',
    '教室',
    '昨年|去年',
    '切る',
    '着る',
    '綺麗',
    '銀行',
    'キロ/キロメートル',
    '楽',
    '音',
    '横',
    '本棚',
    '薬',
    '薬を飲む',
    '薬をつける',
    '下さい',
    '座って下さい',
    '果物',
    '果物屋',
    '靴',
    '靴下',
    '国',
    '曇り',
    '曇る',
    '暗い',
    'クラス',
    'グラム',
    '来る',
    '黒い',
    '黒髪',
    '黒帯',
    '警官',
    '今朝',
    '消す',
    '結構',
    '結婚',
    '玄関',
    '元気',
    '公園',
    '交差点',
    '紅茶',
    '交番',
    '声',
    'コート',
    '答える',
    '今年',
    '言葉',
    '困る',
    '困り顔',
    '今月',
    '今月末',
    '今週',
    '今晩',
    '財布',
    '咲く',
    '作文',

    '差す',
    '雑誌',
    '砂糖',
    '散歩',
    '散歩する',
    '塩',
    'しかし',
    '辞書 | 字引',
    '静か',
    '静かに',
    '質問',
    '質問する',
    '自転車',
    '自動車',
    '自分',
    '閉まる',
    '閉める',
    '締める',
    '写真',
    'シャツ',
    'シャワー',
    '授業',
    '程',
    '別',
    '全く',
    '船長',
    '宿題',
    '上手',
    '丈',
    '丈夫',
    '正油',
    '知る|識る',
    '神のみぞ知る',
    '新聞',
    '吸う',
    'スカート',
    '少ない',
    '少なくとも',
    '直ぐに',
    '少し',
    '京',
    '京都',
    '京大 (abréviation de 京都大学)',
    '東京',
    'スマホ',
    '賑やか',
    '旅行',
    '涼しい',
    'ストーブ',
    'スプーン',
    'スポーツ',
    'ズボン',
    '住む',
    'スリッパ',
    'する (rarement 為る)',
    '座る',
    '背が高い',
    '背が低い',
    '生徒',
    '節電',
    '節水',
    '経済',
    '狭い',
    '先月',
    '先週',
    '先生',
    '週末',
    '古い',
    '弁護士',
    '頭がいい',
    '息子',
    '看護士',
    '時々|時時| 時どき',
    '童画 | 動画',
    '優しい',
    '欲しい',
    '汁',
    '洗濯',
    '全部',
    '掃除',
    'そうして/そして',
    'そこ',
    'その',
    'そば',
    'それ',
    'それから',
    'それでは',
    '大変',
    '大学',
    '大使館',
    '大丈夫',
    '大好き',
    '大切',
    '沢山',
    'タクシー',
    '出す',
    'お金を出す',
    '立つ',
    '財宝',
    '探す',

    '時代',
    '冒険',
    '島',
    '思う',
    '茸 | 蕈 | 菌',
    '蛇',
    '異世界',
    '冊',
    '関係',
    '寿司',
    '達',
    '俺',
    '次',
    '気持ち',
    '持つ',
    '待つ',
    '山賊',
    '助く',
    '許す',
    '頼む',
    '建物',
    '楽しい',
    '多分',
    '食べ物',
    '誕生日',
    '段々',
    '近い',
    '地下鉄',
    '地図',
    '逃げる',
    '腰',
    '失せろ',
    '失望',
    '失礼します',
    '恩に着る',
    '町',
    '帽子',
    '茶碗',
    '丁度',
    '一寸',
    '一日',
    '渦',
    '様',
    '勿論',
    '良く',
    '有名 | 名声',
    '富',
    '悲しい',
    '改札',
    'ゴミ箱',
    '一階',
    '二階',
    '地下',
    '近い',
    '遠い',
    'コンセント',
    '出口',
    '自販機',
    '作る | 創る | 造る',
    '正弦',
    '正',
    '締盟',
    '締切日',
    '点ける',
    '勤める',
    '詰まらない',
    '強い',
    '強健',
    'テーブル',
    '手紙',
    '出来る',
    '検査 | テスト',
    'デパート',
    'でも | だが',
    '天気',
    '獣',
    '魔',
    '魔法',
    '賞金',
    '訳',
    '基地',
    '目的',
    '目的地',
    '店',
    '縄',
    '変',
    '罪',
    '約束',
    '寛い',
    '広い | 廣い',
    '掃除機',
    '洗濯機',
    '冷蔵庫',
    '大佐',
    '早い',
    '早く',
    '早口',
    '早朝',
    '決める',
    '宝',

    '飛ぶ',
    '理由',
    '目',
    '的',
    '電気',
    '戸棚',
    '戸',
    '戸外',
    '神戸',
    'どう',
    'どうして',
    'どうぞ',
    'どうも',
    '動物',
    '十日',
    '時計',
    '何処',
    '部屋',
    '盾',
    '血',
    '負け',
    '勝者',
    '二刀流',
    '弱',
    '弱い',
    '必ず',
    '娘',
    '秘密',
    '所',
    '図書館',
    'どちら',
    'どっち',
    'とても',
    'どなた (forme honorifique de 誰)',
    '止まる',
    '友達',
    '鳥',
    '取る',
    '撮る',
    'ナイフ',
    '鳴く',
    '鳴く猫は鼠を捕らぬ',
    '亡くす | 無くす | 失くす',
    '何故',
    '夏',
    '寂しい',
    '駄目',
    '動く',
    '驫',
    '轟く',
    '轟かす',
    '鞭',
    '我々',
    '身分',
    '夢',
    '倒れる',
    '喜んで',
    '乗り込む',
    '海図',
    '専門',
    '泥棒',
    '不味い',
    '空',
    '空手',
    'ホーム',
    '走る',
    '乗り換え',
    '乗換切符',
    '彼氏',
    '韓国',
    '趣味',
    'もう直ぐ',
    '終点',
    '永い',
    '引っ越す',
    'エアコン',
    '私事',
    '事',
    '絵本',
    '二日',
    '舌',
    '科学',
    '航海',
    '興味',
    '音符',
    '楽器',
    '楽園',
    '漫画',
    '読書',
    '意見',
    '発見',
    '発見する',
    '夏休み',
    '等 | 抔',
    '七日',
    '習う',
    '並ぶ',
    '成る',
    '荷物',
    '脱ぐ',

    '温い',
    'ネクタイ',
    'ノート',
    '登る',
    '飲み物',
    '乗る',
    '歯',
    '歯科',
    '灰皿',
    '灰',
    '葉書',
    '茶葉',
    '葉',
    '箱',
    '橋',
    '箸',
    '始まる',
    '始め | 初め',
    '初めて',
    '物語',
    '単語',
    '卵の黄身',
    '卵の白身',
    '食器',
    '今夜',
    '今回',
    '今度',
    '鉄',
    '鉄鋼',
    '鉄剣',
    '二十歳',
    '二十日 ',
    '花',
    '鼻',
    '速い',
    '春',
    '銀行員',
    '飛行機',
    '歩行者',
    '未来',
    '再来週',
    '再来年',
    '再',
    '説明',
    '説明する',
    '証明',
    '証明する',
    '館',
    '水族館',
    '美術館',
    '家賃',
    '一人',
    '一回',
    '第一',
    '二倍',
    '三分の一',
    '三分の二',
    '盗む',
    '存分に',
    '戦い',
    '能力',
    '覚悟',
    '警察',
    '警察犬',
    '警察署',
    '秘密警察',
    '何か',
    '何も',
    '昨夜',
    '親友',
    '達する',
    '何歳',
    '笑',
    '罠を張る',
    '貼る',
    '晴れ',
    '晴れる',
    '番号',
    '半分',
    '引く',
    '弾く',
    '低い',
    '暇',
    '病院',
    '病気',
    '昼',
    '昼御飯',
    '殺す',
    '大事',
    '大体',
    '小麦',
    '小人',
    '小説',
    '説',
    '車椅子',
    '救急車',
    '円弧',
    '空飛ぶ円盤',
    '不安',
    '向い',

    '守る',
    '為',
    '頑張れ',
    '封筒',
    '吹く',
    '服',
    '豚',
    '太い',
    '冬',
    '降る',
    '文章',
    '下手',
    '辺',
    '便利',
    '最新',
    '新宿',
    '同意',
    '速度',
    '音速',
    '中古',
    '故郷',
    '古代',
    '考古学',
    '遅刻',
    '機嫌',
    '細い',
    '曲路',
    '真直ぐ',
    '真っ直ぐ',
    '円い',
    '章',
    '最終章',
    '忘れる',
    '敷地',
    '町民',
    '磨く',
    '歯を磨く',
    '短い',
    '道',
    '三日',
    '緑',
    '皆さん',
    '耳',
    '見る | 観る',
    '皆',
    '六日',
    '難しい',
    '眼鏡',
    'もう',
    'もう一度',
    '女優',
    '恋人',
    '名刺',
    '歌手',
    '歌詞',
    '国歌',
    '手袋',
    '相手',
    '優れる',
    '俳優',
    'もっと',
    '門',
    '八百屋',
    '野菜',
    '易しい',
    '夕方',
    '夕飯',
    '郵便局',
    '雪',
    'ゆっくり',
    '勝手',
    '邪魔',
    '八日',
    '洋服',
    '四日',
    '呼ぶ',
    '夜',
    '立派',
    '料理',
    '零',
    '練習',
    '廊下',
    '若い',
    '分かる',
    '渡す',
    '渡る',
    '仲間',
    '屈辱',
    '狙う',
    '傷',
    '秒',
    '時点',
    '一時間',
    '分化',
    '気分',
    '前回',
    '最後',
    '後輩',
    '1分',
    '2分',
    '3分',
    '4分',
    '5分',
    '6分',
    '7分',
    '8分',
    '9分',
    '10分',
    '15分',
    '30分',
    '当然',
    '都市',
    'お寺',
    '眠い',
    'お菓子',
    '御土産',
    '空港',
    '具合',
    '近く',
    '木の実',
    '会社員',
    '最高',
    '気温',
    '郵便局員',
    '不便',
    '便秘',
    '小便',
    '大便',
    '銀行口座',
    '店員',
    '売店',
    '蔵',
    '在庫',
    '偽る',
    '道化',
    '無礼',
    '冥土',
    '昔',
    '何時か',
]



JLPT5_voc_fr = [
    '(カイ|あう) rencontrer, avoir un accident, une mauvaise expérience',
    '(カイ|あく) ouvrir, être ouvert (bankai)',
    '(あげる) donner, élever, soulever, augmenter',
    '(あさ) matin',
    '(あした) demain',
    '(あさって|みょうごにち) après-demain',
    '(あし) pied, jambe',
    'là-bas',
    '(あそぶ) jouer',
    '(あたたかい) chaud',
    '(あたま) tête',
    '(あたらしい) nouveau (récent, frais)',
    '(しん), nouveau',
    'par là-bas',
    '(あつい) chaud, brulant, lourd',
    '(あに) grand-frère',
    '(あね) grande-soeur',
    'heuu.. | cela',
    'appartement',
    '(あびる) s\'asperger d\'eau, se baigner, être la cible de',
    '(あぶない) dangereux',
    '(あまい) sucré',
    '(あまり) très, trop, exceptionnel (utilisé souvent négativement)',
    '(あお) bleu',
    '(あか) rouge',
    '(きいろ) jaune, ambre',
    '(むらさき) violet',
    '(メイ|あかるい) éclairé, clair',
    '(シュ|あき) automne',
    '(タンジョカイ) fête d\'anniversaire',
    '(あおぞら) ciel bleu',
    '(みあげる) lever les yeux, regarder en haut, admirer, respecter',
    '(あさごはん) petit déjeuner',
    '(あめ) bonbon',
    '(あらう) laver',
    '(あるく) marcher',
    '(であるく) sortir, se promener, faire un tour',
    '(すあしであるく) marcher pieds-nus',
    '(もと|す) base, origine, source, cause',
    'bon, bien',
    'non',
    '(いう) dire',
    '(かげでわるくちをいう) dire du mal de qq\'un dans son dos, médire',
    '(いえ) maison',
    'combien ? (pas un prix)',
    'Combien ça coûte ?',
    '(いけ) étang',
    '(いしゃ) docteur',
    '(くち) bouche',
    '(あく|わる) mal, vice | mauvaise chose/personne',
    '(いす) chaise',
    '(いそがしい|ぼう) occupé',
    '(いたい) douloureux',
    'premier',
    '(いつか) cinquième jour',
    '(ここのか) neuvième jour',
    'quand',
    '(いっしょ) ensemble',
    '(お) corde, lanière, sangle',
    '(いつも) toujours',
    '(いぬ) chien',
    '(いみ) sens, définition',
    '(いもうと) petite soeur',
    '(あじ|み) goût',
    '(みかた) allié, du côté de quelqu\'un',
    '(いや) désagréable',
    '(いりぐち) entrée, porte, voie d\'accès',
    '(いる) être, être présent, exister, se trouver; avoir',
    '(いる) avoir besoin de',
    '(いれる) insérer, mettre, inclure',
    '(いろ) couleur',
    'varié',
    '(うすい) faible, mince, fin, peu épais, léger',
    '(うすいふく) un vêtement léger',
    '(うすいコーヒー) un café fade',
    '(うすいいろ) une couleur claire',
    '(かいぞく) pirate',
    '(おう) roi',
    '(しんしつ) chambre',
    '(だいどころ) cuisine',
    '(さかな) poisson',
    '(うま) cheval',
    '(えいご) anglais',
    '(のむ) boire',
    '(ごぜん) matin (a.m)',
    '(ごご) après-midi (p.m)',
    '(わたし) je, moi',
    '(おきる) se réveiller',
    '(ねる) dormir, se coucher, coucher avec, aller au lit',
    '(うし) vache, bovin',
    '(ぎゅうにゅう) lait',
    '(ぎゅうにく) viande de boeuf',
    '(れいじ) midi, minuit',
    '(にわ) jardin',
    '(かいしゃ) compagnie, entreprise, société',
    '(ねこ) chat',
    '(つくえ) bureau',
    '(うみ) mer',
    '(まど) fenêtre',
    '(たまご) oeuf',
    '(うた) chanson',
    
    '(うたう) chanter',
    '(うまれる) naître, être né',
    '(ばい|う.る) vendre',
    '(うるさい) bruyant',
    '(うわぎ) veste',
    '(え) peinture, dessin, image',
    '(えいが) film',
    '(えいがかん) salle de cinéma, cinéma',
    '(えき) gare',
    'escalator',
    '(えんぴつ) crayon',
    '(おいしい) bon, délicieux, savoureux',
    '(おおい) nombreux',
    '(おおぜい) beaucoup de monde, foule',
    '(おかあさん) mère',
    '(かし) gâteau, pâtisserie',
    '(おく) placer, poser, mettre en place',
    '(おくさん) épouse, maîtresse de maison',
    '(おさけ) saké, alcool',
    '(おさら) assiette',
    '(おじ) mon oncle',
    '(おしえる) enseigner, apprendre (qqch à qq\'un)',
    '(おじいさん) grand-père',
    '(おす) pousser, appuyer, presser',
    '(おそい) tard, tardif; lent',
    '(おちゃ) thé vert',
    '(おてあらい) toilettes, salle de bain',
    '(おとうさん) père, papa',
    '(おとうと) petit-frère',
    '(おとこのこ) garçon',
    '(おととい) avant-hier',
    '(おととし) il y a deux ans, l\'année avant l\'année dernière',
    '(おとな) adulte',
    '(おなか) ventre, estomac',
    '(おなじ) pareil, même, identique',
    '(おにいさん) frère aîné',
    '(おねえさん) soeur aînée',
    '(おばあさん) grand-mère',
    '(おばさん) tante',
    '(おふろ) bain',
    '(おべんとう) boîte à bento',
    '(おぼえる) se souvenir, retenir| ressentir, considérer',
    '(おもい) lourd',
    '(おもしろい) intéressant, amusant, drôle',
    '(およぐ) nager',
    '(おりる) descendre (d\'un véhicule)',
    '(おわる) se terminer, finir',
    '(おんがく) musique',
    '(おんなのこ) fille (enfant)',
    '(がいこく) pays étranger',
    '(がいこくじん) étranger',
    '(かいだん) escalier',
    '(かいもの) courses, achats',
    '(かいものりすと) liste de courses',
    '(かいものにいく) aller faire les courses',
    '(かう) acheter',
    '(かえす) rendre, restituer',
    '(かえる) revenir',
    '(かかる) contracter une maladie, souffrir d\'une maladie',
    '(かぎ) clef, verrou',
    '(がくせい) étudiant',
    '(でんわをかける) téléphoner, appeler',
    '(でんわ) téléphone',
    '(かさ) parapluie',
    '(かす) louer, mettre en location, prêter, donner',
    '(かぜ) vent',
    '(ふうじゃ|かぜ) rhume',
    '(かぞく) (membre d\'une) famille',
    '(かた) forme polie de 人: personne; manière, façon',
    '(なおしかた) Manière de guérir, remède',
    '(あるきかた) façon de marcher, démarche',
    '(かっぷ) tasse, gobelet',
    '(かてい) foyer, ménage',
    '(かのじょ) petite amie, elle',
    '(かれ) lui, il',
    '(だれ) qui',
    '(さい) ans',
    '(りゅうがくせい) étudiant étranger',
    '(がくせいしょう) carte d\'étudiant',
    '(ちがい) différence, erreur',
    '(きょうだい) frères, fratrie (frères et soeurs)',
    '(しまい) soeurs',
    '(りょうしん) parents',
    '(こども) enfant',
    '(すむ) habiter, résider, vivre ensemble (couple)',
    '(しゅっしん) origine, lieu de naissance',
    '(つめたい) froid, frais (toucher)',
    '(さむい) froid (sensation)',
    '(すき) aimé, apprécié',
    '(からい, つらい) piquant, pénible',
    '(しょくどう) salle à manger',
    '(やすい) bon marché, pas cher',
    '(となり) voisin, à côté',
    '(きのう) hier',
    '(べんきょうする) étudier',
    '(しごと) travail, tâche, métier',
    '(しょくよく) appétit',
    '(しょくひ) frais de nourriture, dépense alimentaire',
    '(しょくもつ) aliment',
    '(やすい) pas cher, bon marché (prix)',

    '(ばんごはん) dîner',
    '(きらい) détesté',
    '(よ) monde, société, époque',
    '(すべて) tout, complètement, entièrement',
    '(しに) mourant, mort, inutile; maudit',
    '(はなつ) libérer, lâcher, émettre, répandre',
    '(ぜんせかい) le monde entier',
    '(せかい) monde, univers',
    '(にんげん) être humain',
    '(みなと) port',
    '(むら) village',
    '(はたらく) travailler',
    '(はたらきすぎ) excès de travail, surmenage',
    '(はたらき) action, fonctionnement, capacité',
    '(じかん) temps, heure',
    '(しゅっぱつ) départ',
    '(もんだい) problème',
    '(セン | ふね) bateau',
    '(ていはく) mouillage, ancrage',
    '(かど) coin, angle',
    '(かばん) sac, sac à main',
    '(かびん) vase',
    '(かみ, し) papier',
    'appareil photo',
    '(げつようび) lundi',
    '(かようび) mardi',
    '(すいようび) mercredi',
    '(もくようび) jeudi',
    '(きんようび) vendredi',
    '(にちようび) dimanche',
    '(からだ, てい) corps, apparence/air',
    '(かりる) louer, emprunter',
    '(かんたん) facile, simple',
    '(かれえ) curry',
    '(こよみ) calendrier',
    '(かわ) rivière',
    '(かわいい) mignon, adorable',
    '(かんじ) kanji',
    '(きえる) disparaître',
    '(ぎたあ) guitare',
    '(きたない) sale, dégoûtant, vulgaire',
    '(きっさてん) salon de thé, café, buvette',
    '(きって) timbre',
    '(きっぷ) ticket, billet',
    '(きょう) aujourd\'hui',
    '(きょうしつ) salle de classe',
    '(さくねん|きょねん) l\'année dernière (formel/normal)',
    '(きる) couper, raccrocher',
    '(きる) porter (un vêtement), se vêtir, enfiler; supporter',
    '(きれい) joli (fille), beau/belle, élégant; propre',
    '(ぎんこう) banque',
    'kilomètre (km)',
    '(らく) confortable, facile',
    '(おと) bruit, son',
    '(よこ) à côté de, horizontal',
    '(ほんだな) étagère, bibliothèque',
    '(くすり) médicament, drogue',
    '(くすり を のむ) prendre un médicament (voie orale)',
    '(くすり を つける) = appliquer un médicament (pommade, spray, etc.)',
    '(ください) s\'il-vous-plaît',
    '(すわって ください) Asseyez-vous s\'il vous plait!',
    '(くだもの) fruit',
    '(くだものや) marchand de fruits',
    '(くつ) chaussure',
    '(くつした) chaussettes',
    '(くに | こく) pays, province',
    '(くもり) nuageux',
    '(くもる) se couvrir (nuages, buée, condensation), s\'embuer, s\'assombrir; devenir sombre (ciel, humeur)',
    '(くらい) sombre',
    'classe',
    'gramme',
    '(くる) venir, commencer (je commence à comprendre le japonais)',
    '(くろい) noir',
    '(くろかみ) cheveux noirs',
    '(くろおび) ceinture noire',
    '(けいかん) policier',
    '(けさ) ce matin',
    '(けす) disparaître, effacer, gommer, éteindre',
    '(けっこう) parfait, excellent, suffisant',
    '(けっこん) mariage',
    '(げんかん) entrée, hall d\'entrée, vestibule',
    '(げんき) santé',
    '(こうえん) parc',
    '(こうさてん) croisement, carrefour',
    '(こうちゃ) thé noir',
    '(こうばん) commissariat',
    '(こえ) voix',
    'manteau, court de tennis',
    '(こたえる) répondre',
    '(ことし) cette année',
    '(ことば) mot, langage, parole',
    '(こまる) être embarrassé, gêné, ennuyé par une situation',
    '(こまりがお) air préoccupé, inquiet',
    '(こんげつ) ce mois-ci',
    '(こんげつまつ) fin de ce mois-ci',
    '(こんしゅう) cette semaine',
    '(こんばん) ce soir',
    '(さいふ) portefeuille, porte-monnaie',
    '(さく) fleurir',

    '(さくぶん) composition écrite, écriture, rédaction, dissertation',
    '(さす) entrer, insérer (une carte bancaire par exemple), tendre la main, sortir son épée, un parapluie, briller ...',
    '(ざっし) magazine',
    '(さとう) sucre',
    '(さんぽ) promenade, balade',
    '(さんぽする) se promener, se balader',
    '(しお) sel, goût salé, épreuve',
    'cependant',
    '(じしょ | じびき) dictionnaire',
    '(しずか) calme, silencieux',
    '(しずかに) silencieusement, calmement; Silence !',
    '(しつもん) question',
    '(しつもんする) interroger, questionner',
    '(じてんしゃ) vélo',
    '(じどうしゃ) automobile, voiture',
    '(じぶん) soi, soi-même',
    '(しまる) se fermer, être fermer',
    '(しめる) fermer',
    '(しめる) lier',
    '(しゃしん) photographie, photo',
    '(しゃつ) chemise',
    '(しゃわあ) douche',
    '(じゅぎょう) cours, classe',
    '(ほど) degré, mesure; indication chiffrée + ほど = environ; verbe neutre + ほど = à tel point que',
    '(べつ) différemment, à part, un autre, (mettre) de côté',
    '(まったく) complètement, vraiment, entièrement; bon sang, c\'est pas vrai',
    '(せんちょう) capitaine (d\'un navire) ; longueur d\'un bateau',
    '(しゅくだい) devoirs, exercices',
    '(じょうず) adroit, doué, habile; flatterie',
    '(じょう) jô, unité de mesure : environ 3 mètres',
    '(じょうふ) homme fort, bel homme',
    '(しょうゆ) sauce soja',
    '(しる) savoir, connaître',
    '(かみのみぞしる) Dieu seul le sait (ぞ sert à renforcer l\'expression)',
    '(しんぶん) journal',
    '(すう) aspirer, absorber, fumer',
    'jupe (vient de skirt)',
    '(すくない) peu',
    '(すくなくとも) au moins, au minimum',
    '(すぐに) immédiatement',
    '(すこし) un peu',
    '(みやこ) capitale; 10 puissance 16',
    '(きょうと) Kyoto',
    '(きょうだい) université (prestigieuse) de Kyoto',
    '(とうきょう) Tokyo',
    'smartphone',
    '(にぎやか) animé, bruyant',
    '(りょこう) voyage, excursion',
    '(すずしい) rafraichissant, frais, cool; clair, brillant; imperturbable (visage)',
    'appareil de chauffage transportable (vient de stove)',
    'cuillière (vient de spoon)',
    'sport',
    '(ずぼん) pantalon',
    '(すむ) vivre, habiter, résider',
    'chaussons, pantoufles',
    'faire',
    '(すわる) s\'asseoir',
    '(せがたかい) personne de grande taille',
    '(せがひくい) personne de petite taille',
    '(せいと) élève (soit petit jusqu\'au lycée, soit en rapport avec le suivi d\'un élève)',
    '(せつでん) économie d\'électricité',
    '(せっすい) économies d\'eau',
    '(けいざい) économie (la science)',
    '(せまい) étroit',
    '(せんげつ) le mois dernier',
    '(せんしゅう) la semaine dernière',
    '(せんせい) enseignant, médecin, maître',
    '(しゅうまつ) weekend, fin de la semaine',
    '(ふるい) vieux, ancien (se dit des choses inanimées)',
    '(べんごし) avocat (juriste)',
    '(あたまがいい) intelligent',
    '(むすこ) fils',
    '(かんごし) infirmier/ère',
    '(ときどき) de temps en temps, quelques fois',
    '(どうが) vidéo, animation',
    '(やさしい) gentil, aimable, grâcieux, tendre, doux',
    '(ほしい) désiré, voulu',
    '(しる) bouillon, soupe, jus (soja par exemple)',
    '(せんたく) lessive, lavage',
    '(ぜんぶ) tout, totalité',
    '(そうじ) ménage, nettoyage, balayage',
    'et',
    'là',
    'ce',
    'près, à côté de',
    'cela',
    'après ça, ensuite, et puis...',
    'alors, dans ce cas',
    '(たいへん) très, difficile',
    '(だいがく) université',
    '(たいしかん) ambassade',
    '(だいじょうぶ) sauf, ok, assuré, solide (+ desu => tout va bien, pas de soucis)',
    '(だいすき) adoré/adorer',
    '(たいせつ) important, de valeur',
    '(たくさん) beaucoup',
    'taxi',
    '(だす) faire sortir, envoyer, produire, présenter',
    '(おかねをだす) payer',
    '(たつ) se lever, se mettre debout',
    '(ざいほう) trésor, richesse',

    '(さがす) chercher',
    '(じだい) période',
    '(ぼうけん) aventure, risque',
    '(しま) île',
    '(おもう) penser, croire, imaginer',
    '(たけ) champignon',
    '(へび) serpent (on dit parfois じゃ pour parler d\'un gros serpent ou orochi/daija)',
    '(いせかい) monde parallèle, monde alternatif',
    '(さつ) compteur (pour les manga, revues, cahiers)',
    '(かんけい) relation, rapport (négativement : aucun rapport, rien à voir)',
    '(すし) sushi',
    '(たち) (parfois dachi) suffixe pour indiquer le pluriel',
    '(おれ) je (masculin, avec une certaine prétention)',
    '(つぎ) suivant, prochain',
    '(きもち) sentiment, sensation, émotion',
    '(もつ) tenir, avoir, posséder',
    '(まつ) attendre',
    '(さんぞく) bandit, brigant des montagnes',
    '(たすく) aider, secourir',
    '(ゆるす) pardonner, excuser; permettre, autoriser',
    '(たのむ) demander, prier, faire confiance, confier',
    '(たてもの) immeuble, bâtiment',
    '(たのしい) agréable, amusant, joyeux',
    '(たぶん) peut-être, probablement; beaucoup',
    '(たべもの) nourriture',
    '(たんじょうび) anniversaire',
    '(だんだん) peu à peu, petit à petit',
    '(ちかい) proche, près',
    '(ちかてつ) métro',
    '(ちず) carte, plan',
    '(にげる) s\'enfuir, fuir, s\'échapper',
    '(こし) hanche, dos, bas du dos; flexibilité, élasticité',
    '(うせろ) va-t\'en, disparaît, hors de ma vue ! (se dit à l\'impératif)',
    '(しつぼう) désespoir',
    '(しつれいします) Excusez-moi de vous déranger',
    '(おんにきる) se sentir redevable envers quelqu\'un',
    '(まち) ville (petite ou moyenne), rue, route, quartier',
    '(ぼうし) chapeau, bonnet',
    '(ちゃわん) bol à thé, bol à riz, bol en porcelaine',
    '(ちょうど) juste, justement; correct; exactement',
    '(ちょっと) un peu',
    '(ついたち) le premier du mois; un jour; une journée',
    '(うず) tourbillon',
    '(さま) suffixe honorifique, qui montre le respect',
    '(もちろん) évidemment, bien sûr',
    '(よく) souvent',
    '(ゆうめい | めいせい) gloire; célébrité',
    '(とみ) richesse, fortune',
    '(かなしい) triste',
    '(かいさつ) contrôle de billets (automatique)',
    '(ごみばこ) poubelle',
    '(いっかい) rez-de-chaussée',
    '(にかい) "deuxième" étage (le rez-de-chaussée compte comme le premier)',
    '(ちか) sous-sol',
    '(ちかい) proche, près',
    '(とおい) loin, éloigné, distant',
    'prise de courant, prise électrique',
    '(でぐち) sortie, exit',
    '(じはんき) distributeur automatique',
    '(つくる) créer, fabriquer; élever, cultiver; commettre',
    '(せいげん) sinus (trigonométrie)',
    '(せい) dix mille sextillions (10^40)',
    '(ていめい) formation d\'une alliance, conclusion d\'un traité d\'alliance',
    '(しめきりび) deadline, date limite, dernier délais',
    '(つける) allumer (la lumière)',
    '(つとめる) servir, travailler, être employé à',
    '(つまらない) ennuyeux, nul',
    '(つよい) fort, puissant; résistant, durable',
    '(きょうけん) bonne santé, santé robuste',
    'table',
    '(てがみ) lettre',
    '(できる) pouvoir (faire quelque chose)',
    '(けんさ) test',
    'grand magasin',
    'mais',
    '(てんき) temps, climat',
    '(けもの | じゅう) bête, animal, brute',
    '(ま) magique, diabolique',
    '(まほう) magie, sorcellerie',
    '(しょうきん) prime, récompense (financière)',
    '(わけ) raison, pourquoi',
    '(きち) base (militaire)',
    '(もくてき) but',
    '(もくてきち) destination',
    '(みせ) magasin, boutique, échoppe',
    '(なわ) corde',
    '(へん) étrange, drôle, bizarre',
    '(つみ) faute, péché, crime, délit',
    '(やくそく) promesse, engagement',
    '(ひろい) ouvert d\'esprit',
    '(ひろい) spacieux, large, vaste',
    '(そうじき) aspirateur',
    '(せんたくき) machine à laver le linge',
    '(れいぞうこ) réfrigérateur',
    '(たいさ) colonel, capitaine (marine)',
    '(はやい) tôt; vif, agile, rapide',
    '(はやく) vite, rapidement',
    '(はやくち) qui parle vite, volubile',
    '(そうちょう) de bon matin, de bonne heure',
    '(きめる) décider',

    '(たから) (mon) trésor, qqch de précieux pour soi',
    '(とぶ) voler (dans les airs)',
    '(りゆう) raison',
    '(め) oeil, yeux',
    '(まと | てき) cible, objectif',
    '(でんき) électricité, lumière',
    '(とだな) armoire',
    '(と) porte, portière',
    '(こがい) extérieur, dehors, plein air',
    '(こうべ) Kobe',
    'Comment ? De quelle manière ?',
    'Pour quelle raison ?',
    'S\'il-vous-plaît',
    'Merci',
    '(どうぶつ) animal',
    '(とおか) le 10 du mois; 10 jours',
    '(とけい) horloge, montre',
    '(どこ) où',
    '(へや) pièce, chambre',
    '(たて) bouclier',
    '(ち) sang',
    '(まけ) défaite',
    '(しょうしゃ) vainqueur',
    '(にとうりゅう) style de combat à deux épées',
    '(じゃく) à peine; faiblesse, faible',
    '(よわい) faible, fragile',
    '(かならず) sans faute, impérativement; certainement',
    '(むすめ) fille',
    '(ひみつ) secret',
    '(ところ) endroit, place, lieu',
    '(としょかん) bibliothèque',
    'lequel, par où ?',
    'lequel, laquelle',
    'très',
    'qui',
    '(とまる) s\'arrêter, faire une pause; se poser, se percher, se jucher',
    '(ともだち) ami',
    '(とり) oiseau',
    '(とる) prendre, saisir; voler; enlever, ôter; jouer, se battre contre',
    '(とる) prendre une photo, filmer',
    'couteau',
    '(なく) chanter (oiseau), aboyer, siffler (bruit d\'animaux)',
    '(なくねこわねずみをとらぬ) Ce ne sont pas ceux qui parlent beaucoup qui en font le plus (expression); littéralement : Un chat qui miaule n\'attrape pas de souris',
    '(なくす) perdre (un être cher, quelque chose); égarer',
    '(なぜ) pourquoi ?',
    '(なつ) été',
    '(さびしい) souffrant de solitude; solitaire',
    '(だめ) inutile, sans espoir, impossible; interdit, mauvais',
    '(うごく) bouger; fonctionner; opérer; changer',
    '(とどろき) de nombreux oiseaux',
    '(とどろく) être connu; palpiter',
    '(とどろかす) faire résonner un son; faire savoir qqch au monde entier; faire battre (coeur)',
    '(むち) fouet, cravache',
    '(われわれ) nous',
    '(みぶん) condition, rang, classe, position',
    '(ゆめ) rêve',
    '(たおれる) tomber, s\'évanouir, succomber, mourir; être battu; être bloqué au lit',
    '(よろこんで) avec plaisir, volontiers',
    '(のりこむ) embarquer, monter dans, entrer, aider',
    '(かいず) carte marine',
    '(せんもん) spécialité',
    '(どろぼう) voleur, cambrioleur',
    '(まずい) mauvais, de mauvais goût, peu appétissant',
    '(から) vide',
    '(からて) karate',
    'quai; accueil; maison, chez soi',
    '(はしる) courir; voyager; conduire; se dépêcher de; s\'écouler',
    '(のりかえ) changement, correspondance; enjambement',
    '(のりかえきっぷ) billet de correspondance',
    '(かれし) petit ami',
    '(かんこく) Corée du Sud',
    '(しゅみ) passe-temps',
    '(もうすぐ) dans très peu de temps, sur le point de',
    '(しゅうてん) terminus',
    '(ながい) de longue durée',
    '(ひっこす) déménager',
    'climatiseur',
    '(しじ) affaire personnelle',
    '(こと | じ) chose, affaire, fait; incident; situation',
    '(えほん) livre d\'images',
    '(ふつか) le deux du mois; deux jours',
    '(した) langue',
    '(かがく) sciences',
    '(こうかい) navigation',
    '(きょうみ) intérêt',
    '(おんぷ) note de musique',
    '(がっき) instrument (de musique)',
    '(らくえん) paradis',
    '(まんが) manga',
    '(どくしょ) la lecture',
    '(いけん) avis, opinion',
    '(はっけん) découverte',
    '(はっけんする) découvrir',
    '(なつやすみ) vacances d\'été',
    '(など) par exemple, etc, entres autres',
    '(なのか) 7ème jour; 7 jours',
    '(ならう) apprendre; prendre des leçons, prendre des cours',
    '(ならぶ) faire la queue; aligner, s\'aligner',
    '(なる) devenir, grandir, pousser, réussir',
    '(にもつ) bagage; fardeau',

    '(ぬぐ) enlever ses vêtements',
    '(ぬるい) tiède',
    'cravatte',
    'cahier',
    '(のぼる) monter, grimper, s\'élever; être promu',
    '(のみもの) boisson',
    '(のる) monter (dans un véhicule)',
    '(は) dent',
    '(しか) cabinet dentaire',
    '(はいざら) cendrier',
    '(はい) cendre',
    '(はがき) carte postale',
    '(ちゃば) feuille de thé',
    '(は | よう) feuille d\'arbre | compteur (choses fines et plates : feuilles d\'arbres ou de papier)',
    '(はこ) boîte',
    '(はし) pont',
    '(はし) baguettes (pour manger) : ils mangent avec des ponts ahah',
    '(はじまる) commencer, débuter; se produire à nouveau; dater de',
    '(はじめ) début',
    '(はじめて) pour la première fois, premièrement, pour commencer',
    '(ものがたり) compte, récit',
    '(たんご) mot, vocabulaire',
    '(たまごのきみ) jaune d\'oeuf',
    '(たまごのしろみ) blanc d\'oeuf',
    '(しょっき) vaisselle',
    '(こんや) ce soir, cette nuit',
    '(こんかい) cette fois-ci',
    '(こんど) maintenant, cette fois, la prochaine fois, une autre fois',
    '(てつ) fer',
    '(てっこう) acier',
    '(てっけん) épée en fer',
    '(はたち) 20 ans',
    '(はつか) le 20 du mois; vingt jours',
    '(はな) fleur',
    '(はな) nez',
    '(はやい) rapide',
    '(はる) printemps',
    '(ぎんこういん) employé de banque',
    '(ひこうき) avion',
    '(ほこうしゃ) piéton',
    '(みらい) futur; le monde à venir',
    '(さらいしゅう) dans deux semaines',
    '(さらいねん) dans deux ans',
    '(さい) re-, encore, à nouveau, répété, pour la deuxième fois',
    '(せつめい) explications',
    '(せつめいする) expliquer, éclairer',
    '(しょうめい) preuve',
    '(しょうめいする) prouver, démontrer',
    '(かん) grand bâtiment; bâtiment public',
    '(すいぞくかん) aquarium',
    '(びじゅつかん) musée d\'art, galerie d\'art',
    '(やちん) loyer',
    '(ひとり) une seule personne; tout seul',
    '(いっかい) une fois',
    '(だいいち) premier, numéro 1',
    '(にばい) double, deux fois',
    '(さんぶんのいち) un tiers',
    '(さんぶんのに) deux tiers',
    '(ぬすむ) pillier, voler',
    '(ぞんぶんに) sans réserve, à satiété',
    '(たたかい) bataille',
    '(のうりょく) compétence, talent, aptitude, factulté',
    '(かくご) détermination, résolution, résignation; savoir, connaissance',
    '(けいさつ) police',
    '(けいさつけん) chien policier',
    '(けいさつしょ) commissariat de police',
    '(ひみつけいさつ) police secrète',
    '(なにか) quelque chose',
    '(なにも) rien',
    '(さくや | ゆうべ) hier soir, la nuit dernière',
    '(しんゆう) ami intime, confident',
    '(たっする) atteindre',
    '(なんさい) Quel âge ?',
    '(わら) rire (utilisé par les jeunes surtout : lmao, rofl, mdr, lol,...)',
    '(わなをはる) tendre un piège, une embuscade',
    '(はる) coller; être cher; étirer, tendre',
    '(はれ) beau temps, temps clair; innocenté',
    '(はれる) s\'éclaircir, se dégager, se dissiper; être banni',
    '(ばんごう) numero, nombre',
    '(はんぶん) trente secondes',
    '(ひく) tirer (une porte vers soi), retirer sa main, ...; jouer d\'un instrument (à cordes); soustraire',
    '(ひく) jouer d\'un instrument à cordes/piano',
    '(ひくい) bas, peu élevé, petit',
    '(ひま) de repos, libre; temps libre',
    '(びょういん) hôpital',
    '(びょうき) maladie',
    '(ひる) midi; déjeuner',
    '(ひるごはん) déjeuner (le midi)',
    '(ころす) tuer',
    '(だいじ) important; affaire sérieuse',
    '(だいたい) en gros, à peu près; en général',
    '(こむぎ) blé',
    '(こびと | しょうにん) nain, enfant (âge d\'être en primaire)',
    '(しょうせつ) roman, nouvelle',
    '(せつ) théorie',
    '(くるまいす) fauteuil roulant',
    '(きゅうきゅうしゃ) ambulance',
    '(えんこ) arc de cercle',
    '(そらとぶえんばん) soucoupe volante',
    '(ふあん) anxiété, angoisse, inquiétude',

    '(むかい) opposé; en face; autre côté',
    '(まもる) protéger, garder, respecter; obéir, observer, suivre, tenir une promesse',
    '(ため) intérêt, but raison',
    '(がんばれ) courage ! bon courage ! Tiens bon !',
    '(ふうとう) enveloppe',
    '(ふく) souffler, jouer d\'un instrument à vent; siffler; émettre',
    '(ふく) vêtement',
    '(ぶた) cochon',
    '(ふとい) gros, gras, épais',
    '(ふゆ) hiver',
    '(ふる) tomber (la pluie, la neige)',
    '(ぶんしょう) texte, phrase, prose; style littéraire',
    '(へた) maladroit, peu doué',
    '(へん | ほとり) voisinage, proximité, zone | voisinage d\'un point d\'eau',
    '(べんり) pratique, commode, utile',
    '(さいしん) le plus récent, le dernier en date',
    '(しんじゅく) Shinjuku',
    '(どうい) accord, consentement, approbation',
    '(そくど) vitesse',
    '(おんそく) vitesse du son',
    '(ちゅうこ) occasion, seconde main; Moyen Âge',
    '(こきょう) pays natal, village natal',
    '(こだい) antiquité',
    '(こうこがく) archéologie',
    '(ちこく) retard, manque de ponctualité',
    '(きげん) humeur, bonne humeur; santé, bien-être',
    '(ほそい) mince, fin, menu',
    '(きょくろ) route sinueuse',
    '(まっすぐ) tout droit',
    '(まっすぐ) direct, honnête, franc',
    '(まるい) rond, circulaire',
    '(しょう) chapitre, section',
    '(さいしゅうしょう) dernier chapitre (sens propre ou figuré)',
    '(わすれる) oublier',
    '(しきち) emplacement, terrain, parcelle, terres',
    '(ちょうみん) habitants d\'une ville, citadins',
    '(みがく) polir, brosser, nettoyer',
    '(はをみがく) se brosser les dents',
    '(みじかい) court',
    '(みち) chemin, voie, rue, route',
    '(みっか) le 3 du mois, troisjours',
    '(みどり) vert',
    '(みなさん) tout le monde',
    '(みみ) oreille',
    '(みる | みる) regarder, voir | observer, contempler',
    '(みんな) tout le monde, tous',
    '(むいか) 6ème jour (du mois), 6 jours',
    '(むつかしい | むずかしい) difficile, compliqué',
    '(めがね) lunettes',
    'déjà',
    '(もういちど) encore une fois',
    '(じょゆう) actrice',
    '(こいびと) petit ami(e)',
    '(めいし) carte de visite',
    '(かしゅ) chanteur',
    '(かし) paroles d\'une chanson',
    '(こっか) hymne national',
    '(てぶくろ) gant',
    '(あいて) adversaire; destinataire',
    '(すぐれる) exceller',
    '(はいゆう) acteur',
    'plus, encore',
    '(もん) portail',
    '(やおや) marchand de fruits et légumes',
    '(やさい) légume',
    '(やさしい) facile, simple (à comprendre). Contrairement à kantan qui est facile, simple (à faire)',
    '(ゆうがた) soir, soirée, fin d\'après-midi',
    '(ゆうはん) repas du soir, dîner (moins formel que "晩御飯")',
    '(ゆうびんきょく) bureau de poste',
    '(ゆき) neige',
    'lentement, doucement',
    '(かって) à sa guise, sans permission; circonstances',
    '(じゃま) obstacle',
    '(ようか) le huit du mois, huit jours',
    '(ようふく) vêtement (de style occidental)',
    '(よっか) le quatre du mois, quatre jours',
    '(よぶ) appeler, inviter',
    '(よる | や) nuit, soir',
    '(りっぱ) magnifique, majestueux, superbe, louable',
    '(りょうり) cuisine; nourriture',
    '(れい) zéro; rien, vide',
    '(れんしゅう) entraînement, exercice',
    '(ろうか) couloir',
    '(わかい) jeune',
    '(わかる) comprendre, savoir, juger; découvrir',
    '(わたす) remettre (qqch à qq\'un)',
    '(わたる) traverser',
    '(なかま) camarade, ami, associé, partenaire',
    '(くつじょく) humiliation, disgrâce',
    '(ねらう) viser',
    '(きず) blessure',
    '(びょう) seconde',
    '(じてん) moment, instant',
    '(いちじかん) une heure (de durée)',
    '(ぶんか) culture',
    '(きぶん) humeur, disposition',
    '(ぜんかい) dernier, précédent',
    '(さいご) dernier, final, le plus récent',
    '(こうはい) qui a moins d\'ancienneté, cadet',
    '(いっぷん) 1 minute',
    '(にふん) 2 minutes',
    '(さんぶん) 3 minutes',
    '(よんぷん) 4 minutes',
    '(ごふん) 5 minutes',
    '(ろっぷん) 6 minutes',
    '(ななふん) 7 minutes',
    '(はっぷん) 8 minutes',
    '(きゅうふん) 9 minutes',
    '(じゅっぷん) 10 minutes',
    '(じゅうごふん) 15 minutes',
    '(さんじゅっぷん / はん) 30 minutes',
    '(とうぜん) justement, naturellement, évidemment',
    '(とし) grande ville, cité',
    '(おてら) temple bouddhique',
    '(ねむい) avoir sommeil',
    '(おかし) confiserie, bonbon',
    '(おみやげ) souvenir (matériel)',
    '(くうこう) aéroport',
    '(ぐあい) état (de santé souvent), condition',
    '(ちかく) voisinage, environs, alentours (+ no => proche, voisin, + ni => près de, à proximité, + kara => de près)',
    '(このみ) noix, baie, fruit d\'un arbre',
    '(かいしゃいん) salarié d\'une entreprise, employé d\'une entreprise',
    '(さいこう) maximum, le plus haut, le plus élevé, le meilleur',
    '(きおん) température ambiante, température atmosphérique',
    '(ゆうびんきょくいん) postier, facteur',
    '(ふべん) incommode, pas pratique',
    '(べんぴ) constipation',
    '(しょうべん) petite commission (pipi)',
    '(だいべん) grosse commission (caca)',
    '(ぎんこうこうざ) compte en banque',
    '(てんいん) vendeur, employé du magasin',
    '(ばいてん) kiosque, stand, boutique',
    '(くら) grenier, entrepôt, grange, depôt',
    '(ざいこ) stock',
    '(いつわる) dissimuler, tromper, duper, feindre',
    '(どうけ) clown',
    '(ぶれい) impoli, malpoli',
    '(めいど) Les Enfers, le monde souterrain, le royaume des morts',
    '(むかし) autrefois, le temps passé',
    '(いつか) un jour..., en temps voulu',
]




JAP_SENTENCES = [
    '彼はどこに行きますか？',
    '彼女の名前は何ですか？',
    '彼にはお兄さんが三人います',
    'あなたのご両親は英語が話せますか?',
    '私は寒い | 寒いです',
    '私の手は冷たいです | 手が冷たいです',
    '猫が好きです。',
    '私はあなたを愛しています。',
    '好きな人がいますか。',
    '彼女達は姉妹です',
    'すみません、あなたは誰ですか？',
    'それは何時間かかりますか？',
    '時間がない',
    '出発の時間です；出発の時間になりました。',
    'それは時間の問題だけです',
    '彼はいつ来ますか？',
    '私は三十一時間働きます',
    '毎日、忙しいです',
    '私の後ろに椅子があります',
    '十冊の本があります',
    '昨日は家にいました',
    'あなたはいつ来ますか？',
    'アアー日本語が分かって来た',
    '別の人です',
    'それは全く関係がない、全く違うことです | 全く別のことです',
    '何をしているのですか？',
    '私は何もすることがありません',
    '私は時々父とスポーツをします',
    'ラーメンていしょくを四つください',
    '少し大きいですね',
    'いつも七時半にヨガをします',
    'このお茶は少し小さいですね',
    '可愛いコートが欲しいです',
    'ああ、おにぎりを三つ下さい',
    '明日、何時にバスケットボールをしますか',
    '私の彼女も空手をします',
    '日本の映画を見ますか？',
    'ナオミさん、どんな本が好きですか？',
    '本当ですか？私も空手をします',
    '一人で音楽を聞きます',
    'よくヨガをしますか？',
    'この鞄はとても古いです',
    '日本の映画を見ますか？',
    '次のバスはもうすぐ来ます',
    'あのバスは上野公園に行きます',
    'この電車は速いですね',
    'まだその古いアパートに住んでいますか？',
    '十二時半ごろ昼御飯を作ります',
    '何時に帰りますか',
    '今 、映画館へ行きます',
    '明日何時に家へ来ますか',
    '昨日何をしましたか',
    '友達とデパートへ行きました',
    'そうですか。何か買いましたか',
    '何も買いませんでした。でも今晩また行きますよ。一緒に行きましょう。',
    'そうしましょう',
    '誰と行きましたか',
    '華子と日本へ行きました',
    '何も食べませんでした',
    '今晩、魚を食べましょう',
    '明日、映画館へ行きましょう',
    'バイオリンを弾く',
    'いいえ、私のではありません。私のは大きいです、でもそれは小さいです',
    '大きくて速い車がほしいです。速くない車が嫌いです',
    'いいえ、私のではありませんが、すぐに同じ車を買います',
    '私は耳で音符を聞き分けることができます',
    'この車は古くて遅いです',
    '昨日、先生とデパートへ行きました。新しくて大きくてあかいテレビを買いました',
    '今朝友達の家で犬を見ました。同じのがほしいです',
    '映画館へ行きましたが、よくなかったです',
    'どの車はあなたのですか。私のは先生の車と同じですが、すぐ新しいのかいます',
    'あの女の人は有名ですね',
    'はい、有名な人です。日本の歌手です',
    'はい、とてもきれいです。また優しそうな人です',
    'あのやさしくてきれいな歌手は誰ですか',
    'このケーキはおいしそうですが、あまくなくて高かったです',
    '料理が嫌いです',
    '9時45分です',
    '何時に帰りますか',
    'ここは本とんに有名な所です',
    'はい、少し座ります',
    'すみません、医者をお願いします',
    '救急車はもうすぐに行きますか',
    'これは私の電話番号です',
    '多分、５時間くらいかかります',
    '雨の日は本を読みます',
    '晴れの日はよく公園に行きます',
    'ご両親の電話番号をお願いします',
    '郵便局はどこにありますか',
    '駅の前にあります',
    '郵便局の隣に何がありますか',
    '冷蔵庫の中にあります',
    'りんごはどこにありますか',
    '銀行はどこですか | 銀行はどこにありますか',
    '猫はテーブルの上にいます',
    '犬はテーブルの下にいます',
    'リモコンはテレビの前にあります',
]


FR_SENTENCES = [
    'Où va-t-il ?',
    'Quelle est son nom ? (son féminin)',
    'Il a trois grands frères.',
    'Est-ce que tes parents parlent anglais ?',
    'J\'ai froid | Il fait froid',
    'J\'ai les mains froides | J\'ai froid aux mains',
    'J\'aime les chats.',
    'Je t\'aime',
    'Avez-vous un être cher (un amoureux) ?',
    'They are sisters',
    'Excusez-moi, qui êtes-vous ?',
    'combien d\'heure cela prend-t\'il ?',
    'je n\'ai pas le temps',
    'c\'est l\'heure de partir; il est temps de partir',
    'ce n\'est qu\'une question de temps',
    'Quand arrive-t-il ?',
    'Je travaille pendant 31 heures.',
    'Je suis occupé tous les jours.',
    'Il y a une chaise derrière moi',
    'Il y a 10 livres.',
    'Je suis resté à la maison hier',
    'Quand viens-tu ?',
    'Ah, je commence à comprendre le japonais.',
    'c\'est quelqu\'un d\'autre',
    'ça n\'a rien à voir c\'est complètement autre chose',
    'Qu\'est-ce que tu fabriques ?',
    'Je n\'ai rien à faire',
    'Je fais parfois du sport avec mon père.',
    'Quatre bols de ramen, s\'il vous plaît.',
    'C\'est un peu grand, n\'est-ce pas ?',
    'Je fais toujours du yoga à 7h30',
    'Ce thé est plutôt petit, n\'est-ce pas ?',
    'Je veux ce blouson mignon',
    'Ah, trois onigiri s\il-vous-plaît',
    'Demain, à quelle heure fais-tu du baseketball ?',
    'Ma copine fait également du karaté',
    'Est-ce que tu regardes des films japonais ?',
    'Naomi, quels livres aimes-tu ?',
    'Vraiment ? Moi aussi, je fais du karaté !',
    'J\'écoute de la musique tout seul.',
    'Faites-vous souvent du yoga ?',
    'Ce sac est très vieux.',
    'Regardez-vous des films japonais ?',
    'Le prochain bus arrive bientôt.',
    'Ce bus va au parc Ueno.',
    'Ce train est rapide, n\'est-ce pas ?',
    'Habitez-vous toujours dans cet ancien appartement ?',
    'Je vais préparer le déjeuner vers douze heures et demie.',
    'A quelle heure allez-vous rentrer ?',
    'Maintenant, je vais au cinéma.',
    'Demain, à quelle heure viens-tu à la maison ?',
    'Qu\'est-ce que tu as fais hier ?',
    'Je suis allée au centre commercial avec des amis.',
    'Ah oui ? Et tu as acheté quelque chose ?',
    'Non, je n\'ai rien acheté, mais ce soir j\'y retourne. Allons-y ensemble !',
    'Ok, faisons comme ça',
    'Avec qui y es-tu allé ?',
    'Je suis allé au Japon avec Hanako',
    'Je n\'ai rien mangé.',
    'Mangeons du poisson ce soir',
    'Allons au cinéma demain.',
    'Jouer du violon',
    'Non, ce n\'est pas le mien. Le mien est gros, celui-là est petit.',
    'Je veux une voiture grosse et rapide. Je déteste les voitures qui ne sont pas rapides.',
    'Non, ce n’est pas la mienne mais je vais bientôt acheter la même.',
    'Je suis capable de reconnaître les notes de musique à l\'oreille. (J\'ai l\'oreille absolue)',
    'Cette voiture est vieille et lente.',
    'Hier je suis allé au centre commercial avec mon professeur. Nous avons acheté une nouvelle grande télévision rouge.',
    'Ce matin, j\'ai vu un chien chez mon ami. J\'aimerais avoir le même.',
    'Je suis allé au cinéma mais ce n\'était pas super.',
    'Laquelle est votre voiture ? J\'ai la même que notre professeur mais je vais en achter un nouvelle bientôt.',
    'Cette femme est célèbre, n\'est-ce pas ?',
    'Oui, c\'est une personne célèbre. C\'est une chanteuse japonaise.',
    'Oui, très jolie. Elle a aussi l\'air gentille.',
    'Qui est ce gentil et beau chanteur ?',
    'Ce gâteau à l\'air bon, mais il a coûté cher et n\'est pas sucré.',
    'Je n\'aime pas faire la cuisine',
    'Il est 9h45.',
    'A quelle heure rentres-tu ?',
    'On est à un endroit vraiment célèbre.',
    'Oui, je vais m\'assoir un peu',
    'Excusez-moi, je vous prie de m\'appeler un médecin.',
    'L\'ambulance partira-t-elle bientôt',
    'C\'est mon numéro de téléphone',
    'Probablement environ 5h00.',
    'Les jours de pluie, je lis des livres.',
    'Les jours ensoleillés, je vais souvent au parc',
    'Pourriez-vous me donner le numéro de téléphone de vos parents.',
    'Savez-vous où il y a un bureau de poste ?',
    'Il y en a un en face de la gare.',
    'Qu\'y a-t-il à côté du bureau de poste ?',
    'Dans le frigo.',
    'Où est-ce qu\'il y a des pommes ?',
    'Où est la banque ? | Où y a-t-il une banque ?',
    'Le chat est sur la table.',
    'Le chien est sous la table.',
    'La télécommande est devant la télévision.',
]



ROMANJI_SENTENCES = [
    'Kare wa doko ni ikimasu ka?',
    'Kanojo no namae wa nan desu ka?',
    'Kare ni wa onisan ga san-nin imasu.',
    'Anata no ryoushin wa eigo o hanasemasu ka?',
    'Watashi wa samui | Samui desu',
    'Watashi no te wa tsumetai desu | Te ga tsumetai desu',
    'Neko ga suki desu',
    'Watashi wa anata o aishiteimasu',
    'suki na hito ga imasuka',
    'Kanojotachi wa shimai desu.',
    'Sumimasen, anata wa dare desu ka?',
    'Sore wa nanjikan kakarimasu ka?',
    'Jikan ga nai.',
    'Shuppatsu no jikan desu; shuppatsu no jikan ni narimashita.',
    'Sore wa jikan no mondai dake desu.',
    'Kare wa itsu kimasu ka?',
    'Watashi wa sanjuu ichi jikan hatarakimasu.',
    'Mainichi isogashii desu.',
    'Watashi no ushiro ni isu ga arimasu.',
    'Jusatsu no hon ga arimasu.',
    'Kinou wa ie ni imashita.',
    'Anata wa itsu kimasu ka?',
    'Aa, Nihongo ga wakatte kita.',
    'betsu no hito desu',
    'Sore wa mattaku kankei ga nai, mattaku chigau koto desu. | Mattaku betsu no koto desu',
    'Nani o shite iru no desu ka?',
    'Watashi wa nani mo suru koto ga arimasen.',
    'Watashi wa tokidoki chichi to supōtsu o shimasu.',
    'Ramen teishoku wo yottsu kudasai.',
    'Sukoshi ookii desune',
    'Itsumo shichi jihan ni yoga wo shimasu',
    'Kono ocha wa sukoshi chiisai desune',
    'Kawaii kouto ga hoshii desu',
    'Ah, onigiri wo mittsu kudasai',
    'Ashita, nanji ni basukeroboru wo shimasu ka',
    'Watashi no kanojo mo karate wo shimasu',
    'Nihon no eiga wo mimasuka',
    'Naomi san, donna hon ga suki desuka ?',
    'Honto desu ka ? Watashi mo karate wo shimasu',
    'Hitori de ongaku wo kikimasu',
    'Yoku yoga wo shimasuka',
    'Kono kaban wa totemo furui desu',
    'Nihon no eiga wo mimasuka',
    'Tsugi no basu wa mou sugu kimasu',
    'Ano basu wa Ueno koen ni ikimasu',
    'Kono densha wa hayai desune',
    'Mada sono furui apaato ni sundeimasu ka',
    'Juuni jihan goro hirugohan wo tsukurimasu',
    'Nan ji ni kaerimasu ka',
    'Ima, eigakan e ikimasu',
    'Ashita, nan ji ni ie e kimasu ka',
    'Kinou nani wo shimashita ka.',
    'Tomodachi to depâto e ikimashita yo.',
    'Sou desu ka. Nanika kaimashita ka.',
    'Nanimo kaimasen deshita. Demo konban mata ikimasu yo. Issho ni ikimashou.',
    'Sou shimashou',
    'Dare to ikimashita ka.',
    'Hanako to nihon e ikimashita.',
    'Nanimo tabemasen deshita.',
    'Konban, sakana wo tabemashou',
    'Ashita, eigakan e ikimashou',
    'Baiorin wo hiku',
    'Iie, watashi no dewa arimasen. Watashi no wa ookii desu, demo sore wa chiisai desu.',
    'Ookikute hayai kuruma ga hoshii desu. Hayakunai kuruma ga kirai desu.',
    'Iie, watashi no dewa arimasen ga, sugu ni onaji kuruma wo kaimasu.',
    'Watashi wa mimi de onpu o kikiwakeru koto ga dekimasu',
    'Sono kuruma wa furukute hayai desu',
    'Kino, sensei to depaato he ikimashita. Atarashikute ookikute akai terebi wo kaimashita.',
    'Kesa, tomodachi no ie de inu wo mimashita. Onaji no gahoshii desu',
    'Eigakan he ikimashita ga, yokunakatta desu.',
    'Dona kuruma wa anata no desu ka. Watashi no wa sensei no kuruma to onaji desu ga, sugu atarashii no kaimasu.',
    'Ano onna no hito wa yuumei desu ne.',
    'Hai, yuumei na hito desu. Nihon no kashu desu.',
    'Hai, totemo kirei desu. Mata yasashisou na hito desu.',
    'ano yasashikute kirei na kashu wa dare desu ka',
    'kono ke-ku wa oishisou desuga, amakunakute takatta desu',
    'ryouri ga kirai desu.',
    'ku ji yonjuugofun desu',
    'Nanjini kaeri masuka',
    'Koko wa hontoni yumei na tokoro desu',
    'Hai sukoshi suwarimasu',
    'Sumimasen isha wo onegaishimasu',
    'Kyukyusha wa mousugu ni ikimasu ka',
    'Kore wa watashi no denwabangou desu',
    'Tabun, go jukan gurai kakarimasu',
    'Ame no hi wa hon wo yomimasu',
    'Hare no hi wa yoku koen ni ikimasu',
    'Goryoshin no denwabangou wo onegaishimasu',
    'Yuubinkyoku wa doko ni arimasu ka.',
    'Eki no mae ni arimasu.',
    'Yuubinkyoku no tonari ni nani ga arimasu ka.',
    'Reizokou no naka ni arimasu.',
    'Ringo wa doko ni arimasu ka',
    'Ginkou wa doko desu ka | Ginkou wa doko ni arimasuka',
    'Neko wa teeburu no ue ni imasu',
    'Inu wa teenuru no shita ni imasu',
    'Rimokon wa terebi no mae ni arimasu',
]